# Generated by Django 4.2.3 on 2023-07-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=200)),
                ('familia', models.CharField(max_length=200)),
                ('especie', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('ultima_observacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=200)),
                ('familia', models.CharField(max_length=200)),
                ('especie', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('ultima_observacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
