# Generated by Django 4.2.3 on 2023-07-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aves_argentinas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aves',
            old_name='contenido',
            new_name='caracteristicas',
        ),
        migrations.RenameField(
            model_name='fauna',
            old_name='contenido',
            new_name='caracteristicas',
        ),
        migrations.RenameField(
            model_name='flora',
            old_name='contenido',
            new_name='caracteristicas',
        ),
    ]
